### PR TITLE
WIP- Strong attributes for dogs

### PR DESCRIPTION
**Pull request by markottaviani**
Trying to add factories for the nested attributes of the dog, attachments & photos.  

* Failures:

  1) DogsController GET #index user is logged in returns dog as json
     Failure/Error: let!(:dog) { create(:dog) }
     NoMethodError:
       undefined method `attachment=' for #<Dog:0x0000010e290c48>

### CODE REVIEW

**Comment by markottaviani** [comment]
@TheDudeWithTheThing @jayroh any insight welcome.

**Comment by TheDudeWithTheThing** [comment]
I don't think you can use association with a has_many relationship.  you might have to make a trait that adds to the attachments var after the dog is created.

**Comment by markottaviani** [comment]
Okay, I think this is good to go.

**Comment by TheDudeWithTheThing** [comment]
awesome, nothing glaring on my end, everything still works?

:+1:

**Comment by markottaviani** [comment]
haha I think so.  I might run it through the staging server to make sure there isn't any S3 weirdness

**Comment by markottaviani** [comment]
spoke too soon two of these tests fail when trying ot use the :dog_with_photo_and_attachment factory. Also, unable to add photos or attachments to a dog after it is created when manually testing

**Comment by TheDudeWithTheThing** [comment]
yeah that was annoying when I originally wrote tests for it, I don't even think there are docs on how to test that stuff either

**Comment by markottaviani** [comment]
Correction, unable to edit any fields for an existing dog.  

`1 error prohibited this dog from being saved:
There were problems with the following fields:

Attachments attachment can't be blank`

**Comment by markottaviani** [comment]
Think I got a lead

`Unpermitted parameters: _destroy, id`

http://stackoverflow.com/questions/17686440/deletion-of-nested-attributes-does-not-work

**Comment by markottaviani** [comment]
Rolled the testes back to be lest complicated and passing.  Still better off than where we were.  Merging and deploying

**Pull request merged**
