### PR TITLE
General gem updates

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
Updating gems that will be used in Rails 5

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
@markottaviani did you actually make this commit?  	38c095a

**Comment by markottaviani** [comment]
Yeah 38c095aba600a1d10bb1bc510eaf3bbd71257815 was me, why?

**Comment by TheDudeWithTheThing** [comment]
I'm doing lots of weird rebasing, new branches, etc... so just making sure I didn't bring in a random commit

**Comment by TheDudeWithTheThing** [comment]
Oh man, here's hoping for the best!

**Comment by markottaviani** [comment]
So far so good!

Mark

**Pull request merged**
