### PR TITLE
fixes #869 Dog comment history tabs not working on some devices

### LINKED ISSUE #869: Dog comment history tabs don't work on some devices
(low priority)

Go to Dog manager show page for a dog, scroll to the bottom
 
Try clicking on nav-tabs for *All* *Comments* or *History*

Working:
Desktop Chrome 
Desktop Firefox 61

Not Working:
iPhone 6S Safari
Android v8 Galaxy S9  Chrome & Firefox

### PR DESCRIPTION
**Pull request by lazylester**
fix for #869  Dog comment history tabs not working on some devices

### CODE REVIEW

**Comment by markottaviani** [comment]
Thanks for the fix!  What exactly was causing the Firefox issue?  Some quirk of firefox?

**Comment by lazylester** [comment]
Well first I added tests for the #869 problem. Then I ran into the Firefox peculiarity. Firefox will not "click" a link that is off the page, meaning that it's necessary to scroll down to bring the link into view.

**Comment by lazylester** [comment]
just to be clear, in case it wasn't... the Firefox issue relates only to testing, not actual user operation

**Comment by markottaviani** [comment]
> just to be clear, in case it wasn't... the Firefox issue relates only to testing, not actual user operation

Well, there was a problem with the tabs working for some folks.  From testing in browserstack it looks like this fixes it.

**Comment by lazylester** [comment]
yes, this pr was intended to fix the tabs not working.  The issue mentioned that it was for some mobile devices, and in fact it was true for all small formats, even the chrome dev devices simulation. The firefox testing issue was a by-product of the fix.

**Pull request merged**
