### PR TITLE
Adds searching by dog microchip

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**

### CODE REVIEW

**Comment by markottaviani** [comment]
Niiiiiice

Will test this out tonight and deploy

**Comment by markottaviani** [comment]
From looking at some sample microchips they might be an integer.  In those situations, this will throw errors because ```tracking_id_search``` gets triggered.  

A few example microchips: 
```
982001402146472
0A13212243
```

**Comment by TheDudeWithTheThing** [comment]
Yeah I hate that part, we can just have the search term look through all 3 columns, kinda blah but should be ok

**Comment by TheDudeWithTheThing** [comment]
changing now

**Comment by TheDudeWithTheThing** [comment]
k we're good, just added it to the int search too, we're making a mess here!

**Comment by markottaviani** [comment]
hmm, long ints blow this up.

```
PG::NumericValueOutOfRange: ERROR:  value "982000402146472" is out of range for type integer
LINE 1: SELECT  "dogs".* FROM "dogs" WHERE (tracking_id = '982000402...
                                                          ^
: SELECT  "dogs".* FROM "dogs" WHERE (tracking_id = '982000402146472' OR dogs.microchip = '982000402146472')  ORDER BY tracking_id asc LIMIT 30 OFFSET 0
```

**Comment by TheDudeWithTheThing** [comment]
The only other way is to introduce a search field for microchips or truncate the input for the tracking_id field

**Comment by markottaviani** [comment]
Still blowing up, added a test to demo.  Going to muck with it a little bit

**Comment by markottaviani** [comment]
Okay! Now I think we're good to go.

**Pull request merged**
