### PR TITLE
Bump Rails from 5.2.0 to 5.2.1

### PR DESCRIPTION
**Pull request by greysteil**
That. Should be totally backwards compatible, so no code changes required. 🎉

### CODE REVIEW

**Comment by greysteil** [comment]
FYI, I've fixed the current Hakiri warning here, and made the specs more deterministic. Wanted the PR to be green! :octocat:

**Comment by greysteil** [comment]
You're welcome! 🎉 

Would you be up for running [Dependabot](https://dependabot.com) on this repo to help keep the other dependencies up-to-date? I ran it on my fork and it generated [these PRs](https://github.com/greysteil/RescueRails/pulls), all of which look easily mergeable?

You'd be doing me a favour, too - having well-tested open source repos use Dependabot means I can use the data from your test runs to report any bugs back to the library maintainers.

**Comment by markottaviani** [comment]
Sure, we can give it another try.

**Comment by greysteil** [comment]
Awesome, thanks @markottaviani.

You can add it from [this URL](https://github.com/apps/dependabot), and I'll watch this repo and help out with any breaking changes in the initial PRs. :octocat:

**Pull request merged**
