### PR TITLE
most recent photos were not being selected for inclusion

### PR DESCRIPTION
**Pull request by lazylester**
I noticed what appeared to be a bug in the rake task for adoptapet sync. The intention _appears_ to be that the urls of the four most recent photos should be included in the uploaded csv.

However, by inspection of the code, this was not happening, and  a test (see spec/tasks/adoptapet_sync_spec.rb) confirmed that it was not.

### CODE REVIEW

**Comment by lazylester** [comment]
how is it possible... tests were added and coverage went down, with no change in the number of lines of code?

**Comment by lazylester** [comment]
@iantalarico  added "in progress", but shouldn't the label be "code review"? Maybe my understanding of "in progress" is not correct?

**Comment by iantalarico** [comment]
@lazylester This is my bad I started this a long time back but never got far.  Sorry!

**Comment by lazylester** [comment]
@iantalarico I was not aware of any previous work on this, what were you doing?

**Comment by iantalarico** [comment]
@lazylester oh wow never mind.  I thought this was an issue.  I have no idea how i added that label just now... Please ignore.  Sorry for the confusion...

**Pull request merged**
