### PR TITLE
Updates a lot of javascript gems / libraries

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
I attempted to get us up to Rails 5 but we have a bunch of stuff holding us back. This should fix that.  All tests passing locally.

* Updates ruby to 2.3.1
* Updates jquery-rails
* Updates chosen-rails
* Updates jquery-ui-rails
* Updates jquery.inputmask
* Updates bbq.js
* Removes coffee-rails and converts the 1 coffee file photo.js.coffee to js
* Removes anything related to deleting comments from `comments.js` and `CommentsController`
* Cleans up `find_commentable`
* Updates anything using `jquery.live` to `jquery.on`
* Updates newrelic
* Updates rollbar

### CODE REVIEW

**Comment by markottaviani** [comment]
Hot damn awesome.

**Comment by TheDudeWithTheThing** [comment]
Hmm tests on Travis throwing js errors, will do a full app sweep tonight

**Comment by TheDudeWithTheThing** [comment]
oh man all tests passing, almost too easy, I'm skeptical

**Comment by TheDudeWithTheThing** [comment]
The Hakiri warning about JS went away at least, now we've got a new one, can you mark it as a false positive?

@markottaviani

**Comment by markottaviani** [comment]
Sure, I'll be able to check it out tonight.

**Comment by markottaviani** [comment]
False Positive Marked, anything else you wanted to add to this?

**Pull request merged**
