### PR TITLE
Adds endless scrolling to dog search

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
Both gallery and manager views.

Not as much test coverage as I like but you can at least play with it and see how she rides.

### CODE REVIEW

**Comment by markottaviani** [comment]
Sweet!  First impression on Chrome is triggering to load more stuff should be a bit more eager. 

Currently possible to be looking at was appears to be the last records without hitting the bottom of the scroll bar to trigger the load.    Also should probably load more on the first go.

**Comment by TheDudeWithTheThing** [comment]
A bit more eager meaning when the last results are visible it's already loading?

Also we should probably stick to the 30 per page, I set it to 9 so I didn't have to create 100+ dogs locally to test.

**Comment by markottaviani** [comment]
Correct on the eager loading.

**Comment by markottaviani** [comment]
Looks good!   The pagination header/footer should probably get removed and I might add a little spinny loading gif if I can find something cool.  

I'm thinking I'll want to load this over in Staging for some folks to play with to make sure they like it as well.

**Comment by TheDudeWithTheThing** [comment]
cool, the pagination is currently what's used to get the URL from for the next page, there might be a way to hide it but removing it would mean we recreate some free stuff we're getting from `will_paginate`

**Comment by TheDudeWithTheThing** [comment]
any other feedback here?

**Comment by markottaviani** [comment]
hmm, not really.  I'm going to push this up to staging and let some folks mess around with it, and try to get some feedback.

**Comment by markottaviani** [comment]
one bit of feedback from one user.  I think dogs should be tweaked to return a multiple of three on pagination, otherwise we get these gaps in the blocks when scrolling.

76633cf9-8f44-4243-a1ec-386d1c7870c0

**Comment by markottaviani** [comment]
Might just be showing a little weird from the lack of photos.  Gunna merge this, push it and see how it goes!

**Pull request merged**
