### PR TITLE
Front page design changes

### PR DESCRIPTION
**Pull request by larisabainton**
connects to #563

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
hello @larisabainton!  this is great, can you do 2 things before I review, can you rebase and resolve that conflict in `app/views/pages/home.html.erb` and can you post a couple screenshots of what the new layout from your code looks like?  Thank you and welcome to OPH!

**Comment by markottaviani** [comment]
Caught up the feature branch and fixed the merge conflict.  @larisabainton make sure to do a `git pull` on your feature branch to pull everything down before any other updates.  Was their anything specific you had questions on or just a general overall review?

**Comment by markottaviani** [comment]
Screenshots at cloudapp.

https://cl.ly/0M1e2U1k2525

https://cl.ly/0C1a093E2v3F

https://cl.ly/1v2y1F3F3g04

**Comment by larisabainton** [comment]
hey @markottaviani and @TheDudeWithTheThing, sorry I didn't see your comments until now! Like I said in slack today I think the main questions I had were about how to change the formatting so it looks ok on small screens. Maybe the bootstrap upgrade is what's needed!

**Comment by markottaviani** [comment]
A lot of those reviews happen on a facebook group, and they’ll be looking
at the staging site anyway.  Some should be setting up github accounts soon.

If you have a model for doing it page by page that would be great.  I’m a
big fan of small pull requests.

**Comment by lazylester** [comment]
OK, I'll make a PR for the feature/front-page branch that adds BS4.1 for the home page only. But this will certainly break the design changes in this PR, and they'll need to be fixed. 

Ideally there should be OPH review of the design changes before anyone (me or someone else) fixes the things that BS4.1 will break. Is there a way that can happen?

**Comment by markottaviani** [comment]
Yes, I’ll see that’s it’s taken care of.

**Comment by lazylester** [comment]
I note that the carousel images no longer contain links for "Apply for Adoption", "Our Dogs", "Contact". This is causing spec failures and travis-ci build failure.

Is this intentional? (In which case I'll remove the specs that exercise these links) Or is it inadvertent? (in which case I'll add the links back to the carousel images).

**Comment by markottaviani** [comment]
Intentional, you’re free to remove those tests.

**Comment by lazylester** [comment]
I'm trying to understand the intended navigation scheme with the new design...
The links in the "topbar" are partially duplicated by another set of links (light blue, immediately above the carousel, and right-aligned to the page). But the topbar has dropdown menus and a lot of functionality that the new light blue links do not have.

It seems we should either keep the topbar and eliminate the blue navigation, or else make the blue navigation have all the features of the topbar.

**Comment by markottaviani** [comment]
Leave both for now, there are a lot of design decisions to work out still.

**Comment by lazylester** [comment]
ah OK, I'm jumping the gun here. I will just submit a PR against the front-page branch, then, to add BS4.1 selectively, only for the home page, and hopefully the design issues can be resolved with BS4.1 in place iso BS2.3.

**Pull request merged**
