### PR TITLE
Sort Adopters by Last Comment on each App?

### PR DESCRIPTION
**Pull request by markottaviani**
This is an attempt at #497 However it doesn't work right, and I'm not sure exactly how to handle this sort, as I want sort adopters by the timestamp of the most recent comment on their application.

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
@markottaviani close!

https://github.com/ophrescue/RescueRails/pull/498/commits/dcdaadc9bf8dc39b00e82a54d91207fdb8c80cec

**Comment by markottaviani** [comment]
hmm, still doesn't seem to be working right.

**Comment by TheDudeWithTheThing** [comment]
oh yeah, we need to select out the comment with the max(updated_at) and then sort by that, could be tricky

http://stackoverflow.com/a/17179241

**Comment by MatthewDrouin** [comment]
IDK what the database structure is (if there is an easy way to get it let me know) but you should be able to join on a sub select and sort by the updated_at.

SELECT app.*, c.updated_at 
FROM app 
LEFT JOIN (SELECT * FROM comments WHERE 1=1 GROUP BY id ORDER BY comments.updated_at) AS c ON app.id = c.app_id
ORDER BY c.updated_at

Do a left join because I assume you want apps even if there are no comments.

**Comment by MatthewDrouin** [comment]
GROUP BY id should be GROUP BY app_id

**Comment by TheDudeWithTheThing** [comment]
welcome @MatthewDrouin !  from out of nowhere

it's not pretty but it's doing the job, matt was on the right track, let me make sure we're getting good index usage, there might be a more railsy way to do it too

**Comment by MatthewDrouin** [comment]
The rails way of doing it is to probably add a last_comment_date to the app and update that but I never like those solutions :)

**Comment by markottaviani** [comment]
Sweeet @MatthewDrouin for the win!  This is working pretty well.   Going to go ahead and merge.

**Comment by MatthewDrouin** [comment]
Glad I could be of assistance :)

**Pull request merged**
