### PR TITLE
Hotfix/schema and state fixes

### PR DESCRIPTION
**Pull request by markottaviani**
Found some holes in our test coverage for some of the views that use state.   Cleaned up the views and added a few more tests.

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
a foster isn't a user then?  weird that this isn't working

`  alias_attribute :state, :region`

**Comment by markottaviani** [comment]
A foster is a user

**Comment by tobymurray** [comment]
Yikes, my bad. That looks like a decent amount of broken stuff... Thanks for the quick fix, I'll have to be a bit more careful next time.

**Comment by markottaviani** [comment]
No worries! We should have had better tests!

**Pull request merged**
