### PR TITLE
fix for #524 renable commit button after post

### PR DESCRIPTION
**Pull request by markottaviani**
Was able to verify that for comments on dogs or adopters after a comment was posted, the Post button wouldn't re-enable and folks have to refresh the page for the post button to start working again.

This appears to fix the issue.  Though I'm not sure why it started in the first place, or if there is a cleaner way to handle it.   

Thanks!

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
hmm weird, I think the page used to refresh maybe? Will give a closer look tomorrow

**Comment by TheDudeWithTheThing** [comment]
What's really strange is there's nothing obvious that is disabling the button

**Comment by TheDudeWithTheThing** [comment]
I think we're ok to push this just to unblock / unannoy people, maybe make an issue to revisit?

**Comment by markottaviani** [comment]
Sounds good!  Thanks!

**Pull request merged**
