### PR TITLE
Rails 5

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
Rails 5, start the pit!

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
We'll want some massive QA here.  Tests are passing locally but hang every so often, still researching that.  The site works great though, feels a bit more snappy but that might just be me being hopeful.

**Comment by TheDudeWithTheThing** [comment]
this PR is too beefy and is annoying me, going to break some of the gem upgrades out to their own PRs

**Comment by markottaviani** [comment]
kill-bill-escape-from-grave-o

Hey hey, what's left on the todo list for R5, other than I guess getting these tests to pass ?

**Comment by markottaviani** [comment]
Reran the build and it passed!

**Comment by TheDudeWithTheThing** [comment]
like whoa, I need to get back on this, I'm upgrading an app at work which is taking up all my code time, should be done soon though

**Comment by markottaviani** [comment]
Hit an error when attempting to view the edit screen for a dog:

```
An ActionView::Template::Error occurred in dogs#edit:

The `content_tag_for` method has been removed from Rails. To continue using it, add the `record_tag_helper` gem to your Gemfile:
gem 'record_tag_helper', '~> 1.0'
Consult the Rails upgrade guide for details.

app/views/dogs/edit.html.erb:272:in `block (2 levels) in _app_views_dogs_edit_html_erb___3828785623418011511_47455584046140'
```

**Comment by markottaviani** [comment]
Hit this weird on on a local test

```

Randomized with seed 31622
.....FWARNING:  there is already a transaction in progress
............................................................................................................................

Failures:

  1) AdoptersController POST create creates an adopter
     Failure/Error: @connection.async_exec(sql)

     ActiveRecord::StatementInvalid:
       PG::UnableToSend: : ROLLBACK
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:165:in `exec_rollback_db_transaction'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:285:in `rollback_db_transaction'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_db_transaction'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:138:in `rollback'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:183:in `rollback_transaction'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:240:in `rollback_transaction'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/fixtures.rb:999:in `block in teardown_fixtures'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/fixtures.rb:998:in `each'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/fixtures.rb:998:in `teardown_fixtures'
     # /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/fixtures.rb:858:in `after_teardown'
     # ------------------
     # --- Caused by: ---
     # PG::UnableToSend:
     #   /Users/mark/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'

Top 5 slowest examples (32.58 seconds, 77.4% of total time):
  Apply for Adoption Renter fills out adoption application
    15.33 seconds ./spec/features/apply_to_adopt_spec.rb:6
  AdoptersController GET index should be successful
    10.66 seconds ./spec/controllers/adopters_controller_spec.rb:36
  Manage Events Post and View an Event
    2.38 seconds ./spec/features/event_management_spec.rb:7
  Attach an agreement to a user Admin attaches a confidentiality agreement to a user
    2.16 seconds ./spec/features/attach_agreement_to_user_spec.rb:31
  Attach an agreement to a user Admin attaches a foster agreement to a user
    2.06 seconds ./spec/features/attach_agreement_to_user_spec.rb:11

Top 5 slowest example groups:
  Apply for Adoption
    15.33 seconds average (15.33 seconds / 1 example) ./spec/features/apply_to_adopt_spec.rb:3
  Manage Events
    2.38 seconds average (2.38 seconds / 1 example) ./spec/features/event_management_spec.rb:3
  Attach an agreement to a user
    2.11 seconds average (4.22 seconds / 2 examples) ./spec/features/attach_agreement_to_user_spec.rb:3
  Link Dogs to Adoption Applications via Adoption model
    1.9 seconds average (1.9 seconds / 1 example) ./spec/features/link_dogs_to_adopters_spec.rb:3
  AdoptersController
    1.47 seconds average (11.79 seconds / 8 examples) ./spec/controllers/adopters_controller_spec.rb:30

Finished in 42.11 seconds (files took 7.95 seconds to load)
130 examples, 1 failure

Failed examples:

rspec ./spec/controllers/adopters_controller_spec.rb:64 # AdoptersController POST create creates an adopter
```

**Comment by markottaviani** [comment]
So, this seems okay.  I'm going to kick off a few rebuilds on Travis just to see if anything is flaky.  But I'm getting pretty tempted to just push this out

**Comment by TheDudeWithTheThing** [comment]
bold move!  I didn't get a chance to look at anything yet but should have time tonight to check out anything if you need me to

**Comment by markottaviani** [comment]
Cool thanks still some flaky stuff in travis it seems, not sure what the deal is

**Comment by markottaviani** [comment]
Gunna let this run a few times, but I think some of the issues with the flakey tests are all sorted out 👍

**Comment by markottaviani** [comment]
We're looking good, let's keep the Thanksgiving tradition of doing a Rails upgrade going!  Pushing this out in a few minutes and will be monitoring for any weirdness.

**Comment by TheDudeWithTheThing** [comment]
Like whoa!

**Pull request merged**
