### PR TITLE
Feature/#1697 fix followup mailer

### LINKED ISSUE #1697: AdopterFollowupMailer not being sent
The `AdopterFollowupMailer` probably not be triggered because the `status` of the `Adopter` and the `relation_type` of the `Adoption` each get set in the UI as a separate transaction.  So you'll need to asses the change of the relation_type directly when it is changed as its own separate action.   

https://github.com/ophrescue/RescueRails/pull/1678/files#r494656651

### PR DESCRIPTION
**Pull request by ahutnick**
Separates followup mailer and chimp_check / subscribe - separate status and relation_type triggers 
Combines followup mailer and training mailer function - both have same conditions 
Adopters controller rspec - change status to 'completed' - test that only relation_type (not status) triggers emails

closes #1697

### CODE REVIEW

**Review by markottaviani — APPROVED** [review]
Nice refactor, and much easier to read too 👍

**Review by markottaviani — CHANGES_REQUESTED** [review]
So if you mess around w/ changing the adoption relationship, you'll see that the emails don't fire off.  That's because the `adoptions`  value is getting set by calling the `adoptions` controller directly.  

ex:

```
Started PUT "/adoptions/6.json" for 192.168.50.1 at 2020-09-28 22:25:08 +0000
Processing by AdoptionsController#update as JSON
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "adoption"=>{"relation_type"=>"adopted"}, "id"=>"6"}
```

So you'd probably want to move the `training_followup_email` method over to the `Adoption` model and adjust accordingly

**Comment by ahutnick** [comment]
Ok, training_followup shifted to adoptions, and emails appear to be fired off: 

`[ActiveJob]   Delayed::Backend::ActiveRecord::Job Create (2.8ms)  INSERT INTO "delayed_jobs" ("handler", "run_at", "created_at", "updated_at", "queue") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["handler", "--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: ActionMailer::DeliveryJob\n  job_id: 3fd7f52c-5948-4712-b1a4-4b03f10a2571\n  provider_job_id: \n  queue_name: mailers\n  priority: \n  arguments:\n  - TrainingMailer\n  - free_training_notice\n  - deliver_now\n  - 1\n  executions: 0\n  locale: en\n"], ["run_at", "2020-09-29 19:15:42.877834"], ["created_at", "2020-09-29 19:15:42.877890"], ["updated_at", "2020-09-29 19:15:42.877890"], ["queue", "mailers"]]
[ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: 3fd7f52c-5948-4712-b1a4-4b03f10a2571) to DelayedJob(mailers) with arguments: "TrainingMailer", "free_training_notice", "deliver_now", 1`

`[ActiveJob]   Delayed::Backend::ActiveRecord::Job Create (1.5ms). . .`

**Review by markottaviani — APPROVED** [review]
Nice 👍

**Pull request merged**
