### PR TITLE
Adds column woof_bark_password to users

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
Step 1 here:
https://github.com/ophrescue/RescueRails/issues/947

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
what version of postgres are we on?  I'm assuming the removal of limits from the schema.rb are ok since we aren't doing a `rake db:schema:load` anywhere.

**Comment by lazylester** [comment]
I note that the build failure is in a place where we've seen occasional failures before. I need to look into why this is happening.

**Comment by TheDudeWithTheThing** [comment]
I’m not forcing a reset, you didn’t read my plan in the issue did you?

**Comment by lazylester** [comment]
no, @TheDudeWithTheThing , I didn't read your plan. I didn't know it was there.

But now I've read it, thanks for the heads-up.

I don't really understand the rationale for the approach, but that doesn't matter, no explanation required. As long as it's all seamless to the users, I'm good with it. Last time we discussed it, you didn't see it as a big deal for the users to reset their passwords, and that's where we differ.

**Comment by TheDudeWithTheThing** [comment]
I’m on board. The gist is with your plan we end up with a column named bcrypt_password which fights the gem. I’m just making a column up front for our woofbark password strategy so that bcrypt will only ever use the encrypted_password column.

**Comment by lazylester** [comment]
Yes, the plan I suggested mentioned a second password field. But after suggesting that, I noticed that Clearance has a way to do it without a second field b/c they have a way to read the encrypted password and know what algorithm was used. I learned this after I had suggested a second field, as you mention.

**Pull request closed without merging**
