### PR TITLE
Title cleanup

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
I branched this off of my upgrade all the things branch so the diff looks like a mess.  The big thing to look at is do we want to change titles to live in the `en.yml` file?  Cleans up the controllers a ton, one spot to edit them, you can send en.yml to non-programmers and have them edit it.

The main commit https://github.com/ophrescue/RescueRails/commit/232c12da810ba15b836d84093c85e954a96d13dc

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
check out the pages controller

https://github.com/ophrescue/RescueRails/commit/232c12da810ba15b836d84093c85e954a96d13dc#diff-cc6e703301c6ed33065f186cec0d2939R2

@markottaviani

**Comment by markottaviani** [comment]
I'm good with the move to the yml file

Mark

**Comment by markottaviani** [comment]
Also, since you're branching off the JS upgrade branch I'll assuming you didn't have any other changes to make to it.  I'm going to be pushing that out probably early Tuesday morning so I can baby sit it a little bit in case anything weird pops up.

**Comment by TheDudeWithTheThing** [comment]
Yeah if I have any other changes I'll just make a new PR. It's currently in a deployable state now so no need to touch it.

This PR needs more titles moved to `en.yml` though, will comment when complete

**Comment by TheDudeWithTheThing** [comment]
Also @jayroh approved of this approach   😃

**Comment by markottaviani** [comment]
Looks good to me, however it does look like we're getting some flaky tests in Travis.  Worth putting those hard pauses back in possibly?

**Comment by TheDudeWithTheThing** [comment]
alright added the sleeps back in, passing tests, cash money

**Pull request merged**
