### PR TITLE
Fixes the ranking for real

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
What a n00b

What did we learn here?

* to pass in bind params to order by you pass in an array
* bind params will be quoted properly, so don’t do that for normal sorts
* assign results back to the var, don't be a n00b

### CODE REVIEW

**Comment by TheDudeWithTheThing** [comment]
Did we have that sql injection warning before?  It's sanitized with valid values so not sure why it's complaining.

**Comment by markottaviani** [comment]
It didn't flag on the old branch.

**Comment by TheDudeWithTheThing** [comment]
ha

> Confidence level: Weak

**Comment by TheDudeWithTheThing** [comment]
It must be flagging now because of the couple of layers involved of string interpolation here. Is there no way to mark it as ok?

**Comment by markottaviani** [comment]
Yeah we can flag it as false positive in Hakiri

**Comment by markottaviani** [comment]
I fixed up the rspec tests for this.  The initial search is working correctly, however if someone attempts to sort the results instead of accepting the default sort, the results aren't honored.  The respec tests now break to reflect this, and here is a GIF that shows the behavior as well. 

https://cl.ly/271S0p410Y0r

**Comment by TheDudeWithTheThing** [comment]
What’s the behavior we want? tt will be first always in the current state, only do that when name is the sort column?

**Comment by markottaviani** [comment]
I think the desired behavior is:

When a text search is performed without specifying any sort values, tt is first.

With a text search is performed with sort values, honor the standard sorts.  (don't rank TT first)

**Comment by markottaviani** [comment]
false positive cleared

**Pull request merged**
